const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');

const layout = read('web', 'components', 'Layout.js');
const navigation = read('web', 'components', 'Sidebar.js');
const dashboard = read('web', 'pages', 'dashboard.js');
const login = read('web', 'pages', 'index.js');
const api = read('web', 'lib', 'api.js');
const styles = read('web', 'styles', 'globals.css');
const canvasDashboard = read('web', 'components', 'CanvasDashboard.js');
const tutor = read('web', 'components', 'AIChatWidget.js');
const tutorDrawer = read('web', 'components', 'TutorDrawer.js');
const retain = read('web', 'components', 'QuizMode.js');
const flashcards = read('web', 'components', 'FlashcardViewer.js');
const studyRail = read('web', 'components', 'DashboardStudyRail.js');
const nextConfig = read('web', 'next.config.js');

assert.match(navigation, /className="top-navigation"/);
assert.match(navigation, /className="account-menu-panel"/);
assert.doesNotMatch(layout, /className="app-layout"/);
assert.match(dashboard, /Promise\.allSettled/);
assert.match(dashboard, /finally/);
assert.match(api, /AbortController/);
assert.match(api, /REQUEST_TIMEOUT_MS/);
assert.match(api, /export function apiErrorMessage/);
assert.match(login, /login-mode-tabs/);
assert.match(login, /login-learning-backdrop\.webp/);
assert.match(styles, /\.editorial-page-title/);
assert.match(canvasDashboard, /apiFetch\('\/canvas\/auto-guides', \{ method: 'POST', timeoutMs: 120000 \}\)/);
assert.match(canvasDashboard, /canvasAutoBuildDate/);
assert.match(canvasDashboard, /apiFetch\('\/canvas\/sync', \{ method: 'POST' \}\)/);
assert.match(dashboard, /<CanvasDashboard onWorkspaceChanged=\{refreshCanvasWorkspace\} \/>/);
assert.match(dashboard, /Some Classroom data could not be refreshed/);
assert.match(dashboard, /if \(Array\.isArray\(guidesData\?\.guides\)\) setGuides/);
assert.match(dashboard, /role="alert"/);
assert.match(canvasDashboard, /apiErrorMessage\(data\?\.detail/);
assert.match(styles, /\.canvas-auto-status/);
assert.match(styles, /resize: horizontal/);
assert.match(styles, /resize: vertical/);
assert.match(canvasDashboard, /sort\(\(a, b\) => dueTime\(a\) - dueTime\(b\)\)/);
assert.match(canvasDashboard, /overdueCount/);
assert.match(canvasDashboard, /due within 48 hours/);
assert.match(canvasDashboard, /className="canvas-token-wizard"/);
assert.match(canvasDashboard, /\/profile\/settings/);
assert.match(canvasDashboard, /Open secure connection form/);
assert.match(canvasDashboard, /navigator\.clipboard\.writeText\(cleanDomain\)/);
assert.match(styles, /\.canvas-wizard-overlay/);
assert.match(tutor, /Cordia Tutor/);
assert.match(tutor, /guide\.study_guide \|\| guide\.notes/);
assert.match(tutor, /guide_id: guide\.id/);
assert.match(tutorDrawer, /role="separator"/);
assert.match(tutorDrawer, /cordia:tutor-prompt/);
assert.match(retain, /Explain this question:/);
assert.match(flashcards, /Explain this question:/);
assert.doesNotMatch(retain, /Chatbot being created|requestExplanation/);
assert.doesNotMatch(studyRail, /AIChatWidget/);
assert.match(layout, /<TutorDrawer preferredGuideId=\{activeGuideId\} \/>/);
assert.doesNotMatch(tutor, /requestAnimationFrame|MAX_BUBBLES|stepPhysics/);
assert.match(canvasDashboard, /status: 'building'/);
assert.match(canvasDashboard, /status: 'ready'/);
assert.match(canvasDashboard, /status: 'failed'/);
assert.match(nextConfig, /Strict-Transport-Security/);
assert.match(nextConfig, /X-Content-Type-Options/);
assert.match(nextConfig, /X-Frame-Options/);
assert.match(nextConfig, /Referrer-Policy/);
assert.match(nextConfig, /Permissions-Policy/);

console.log('Production frontend contract passed');
