const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), 'utf8');

const layout = read('web', 'components', 'Layout.js');
const navigation = read('web', 'components', 'Sidebar.js');
const dashboard = read('web', 'pages', 'dashboard.js');
const login = read('web', 'pages', 'index.js');
const api = read('web', 'lib', 'api.js');
const styles = read('web', 'styles', 'globals.css');
const canvasDashboard = read('web', 'components', 'CanvasDashboard.js');
const tutor = read('web', 'components', 'AIChatWidget.js');
const tutorDrawer = read('web', 'components', 'TutorDrawer.js');
const retain = read('web', 'components', 'QuizMode.js');
const flashcards = read('web', 'components', 'FlashcardViewer.js');
const studyRail = read('web', 'components', 'DashboardStudyRail.js');
const classRail = read('web', 'components', 'DashboardClassRail.js');
const createPage = read('web', 'pages', 'create.js');
const smartnotes = read('web', 'pages', 'smartnotes.js');
const nclex = read('web', 'components', 'NCLEXQuizMode.js');
const extensionPopup = read('extension', 'popup.js');
const provenanceMigration = read('supabase', 'migrations', '20260916000000_guide_provenance.sql');
const rlsMigration = read('supabase', 'migrations', '20260915035012_harden_classroom_rls.sql');
const flashcardLibrary = read('web', 'pages', 'flashcards.js');
const guidePage = read('web', 'pages', 'guide', '[id].js');
const folderPage = read('web', 'pages', 'folder', '[id].js');
const nextConfig = read('web', 'next.config.js');
const retainPage = read('web', 'pages', 'quiz', '[guideId].js');

assert.match(navigation, /className="top-navigation"/);
assert.match(navigation, /className="account-menu-panel"/);
assert.doesNotMatch(layout, /className="app-layout"/);
assert.match(dashboard, /Promise\.allSettled/);
assert.match(dashboard, /finally/);
assert.match(api, /AbortController/);
assert.match(api, /REQUEST_TIMEOUT_MS/);
assert.match(api, /export function apiErrorMessage/);
assert.match(api, /response\.headers\.get\('X-Request-ID'\)/);
assert.match(api, /Reference:/);
assert.match(login, /login-mode-tabs/);
assert.match(login, /login-learning-backdrop\.webp/);
assert.match(login, /data\.request_id/);
assert.match(styles, /\.editorial-page-title/);
assert.match(canvasDashboard, /apiFetch\('\/canvas\/auto-guides', \{ method: 'POST', timeoutMs: 120000 \}\)/);
assert.match(canvasDashboard, /canvasAutoBuildDate/);
assert.match(canvasDashboard, /apiFetch\('\/canvas\/sync', \{ method: 'POST' \}\)/);
assert.match(dashboard, /<CanvasDashboard onWorkspaceChanged=\{refreshCanvasWorkspace\} \/>/);
assert.match(dashboard, /Some Classroom data could not be refreshed/);
assert.match(dashboard, /if \(Array\.isArray\(guidesData\?\.guides\)\) setGuides/);
assert.match(dashboard, /role="alert"/);
assert.match(canvasDashboard, /apiErrorMessage\(data\?\.detail/);
assert.match(styles, /\.canvas-auto-status/);
assert.match(styles, /resize: horizontal/);
assert.match(styles, /resize: vertical/);
assert.match(styles, /\.class-guide-popover\s*\{[^}]*background: var\(--surface-raised\)/s);
assert.doesNotMatch(styles, /\.class-guide-popover\s*\{[^}]*transparent[^}]*\}/s);
assert.match(styles, /\.dashboard-left-stack\s*\{[^}]*z-index: 40/s);
assert.match(canvasDashboard, /sort\(\(a, b\) => dueTime\(a\) - dueTime\(b\)\)/);
assert.match(canvasDashboard, /overdueCount/);
assert.match(canvasDashboard, /due within 48 hours/);
assert.match(canvasDashboard, /state\.error \? 'Reconnect Canvas' : 'Connect Canvas'/);
assert.doesNotMatch(canvasDashboard, /CanvasConnectionWizard|canvas-token-wizard|\/profile\/settings|Pipedream/);
assert.doesNotMatch(styles, /\.canvas-wizard-overlay|\.canvas-token-wizard/);
assert.match(tutor, /Cordia Tutor/);
assert.match(tutor, /apiFetch\('\/smart_notes'\)/);
assert.match(tutor, /guide_id: material\.id/);
assert.match(tutor, /note_id: material\.id/);
assert.match(tutor, /context_title: material\.title/);
assert.match(tutor, /\/extract-file-text/);
assert.match(tutor, /find_material: 'Finding Canvas material…'/);
assert.match(tutor, /Based on \{message\.source\.title\}/);
assert.match(createPage, /source_type: externalSourceId\.startsWith\('canvas:'\)/);
assert.equal((smartnotes.match(/source_type: guidePreview\.source\?\.type/g) || []).length, 2);
assert.match(nclex, /source_type: 'study_guide'/);
assert.match(extensionPopup, /source_type: lastSourceType/);
assert.match(extensionPopup, /lastSourceType = source\.selected \? 'selected_text' : 'webpage'/);
assert.match(guidePage, /Based on \{sourceHref/);
for (const column of ['source_type', 'source_title', 'source_id']) assert.ok(provenanceMigration.includes(column));
for (const policy of [
  'Allow insert for authenticated users',
  'Users can insert own guides',
  'Users can update own guides',
  'Users can delete own guides',
  'Users can insert own usage',
  'Users can update own usage',
]) assert.ok(rlsMigration.includes(`drop policy if exists "${policy}"`));
assert.doesNotMatch(rlsMigration, /drop policy[^;]*(?:select|view)/i);
assert.match(rlsMigration, /alter function public\.handle_new_user\(\) set search_path = ''/);
assert.match(rlsMigration, /revoke execute on function public\.handle_new_user\(\) from public, anon, authenticated/);
assert.match(tutorDrawer, /role="separator"/);
assert.match(tutorDrawer, /aria-valuenow=\{width\}/);
assert.match(tutorDrawer, /onKeyDown=\{resizeWithKeyboard\}/);
assert.match(tutorDrawer, /cordiaTutorOpen/);
assert.match(tutorDrawer, /event\.key !== 'Escape'/);
assert.match(tutorDrawer, /cordia:tutor-prompt/);
assert.match(retain, /Explain this question:/);
assert.match(retainPage, /Regenerate questions/);
assert.match(retainPage, /\/quiz\/.*\/regenerate/);
assert.match(retainPage, /method: 'POST'/);
assert.match(flashcards, /Explain this question:/);
assert.doesNotMatch(retain, /Chatbot being created|requestExplanation/);
assert.doesNotMatch(studyRail, /AIChatWidget/);
assert.doesNotMatch([dashboard, canvasDashboard, createPage, flashcardLibrary].join('\n'), /editorial-kicker|dashboard-rail-kicker/);
assert.doesNotMatch([studyRail, classRail].join('\n'), /dashboard-rail-kicker/);
assert.match(guidePage, /Study guide unavailable/);
assert.match(folderPage, /Class unavailable/);
assert.match(guidePage, /role="alert"/);
assert.match(folderPage, /role="alert"/);
assert.doesNotMatch(folderPage, /Unknown Folder/);
assert.match(layout, /!pageOwnsTutor && <TutorDrawer preferredGuideId=\{activeGuideId\} preferredNoteId=\{activeNoteId\} \/>/);
assert.match(tutorDrawer, /if \(docked\)/);
assert.match(tutorDrawer, /tutor-dock-panel/);
assert.doesNotMatch(tutor, /requestAnimationFrame|MAX_BUBBLES|stepPhysics/);
assert.match(canvasDashboard, /status: 'building'/);
assert.match(canvasDashboard, /status: 'ready'/);
assert.match(canvasDashboard, /status: 'failed'/);
assert.match(canvasDashboard, /\/canvas-logo\.svg/);
assert.match(canvasDashboard, /CanvasCapabilities/);
assert.match(canvasDashboard, /<strong>Import classes:<\/strong>/);
assert.match(nextConfig, /Strict-Transport-Security/);
assert.match(nextConfig, /X-Content-Type-Options/);
assert.match(nextConfig, /X-Frame-Options/);
assert.match(nextConfig, /Referrer-Policy/);
assert.match(nextConfig, /Permissions-Policy/);

console.log('Production frontend contract passed');
