import Head from 'next/head';

export default function HonorCode() {
  return (
    <>
      <Head>
        <title>Honor Code — AutoStudyAI</title>
        <meta name="description" content="AutoStudyAI Academic Integrity and Honor Code" />
      </Head>
      <div style={{
        maxWidth: '800px',
        margin: '0 auto',
        padding: '60px 24px',
        fontFamily: "'Segoe UI', -apple-system, sans-serif",
        color: 'var(--text-secondary)',
        lineHeight: '1.8',
      }}>
        <h1 style={{ fontSize: '2rem', fontWeight: '700', color: 'var(--text-primary)', marginBottom: '8px' }}>
          Academic Integrity &amp; Honor Code
        </h1>
        <p style={{ color: 'var(--text-muted)', marginBottom: '40px', fontSize: '0.9rem' }}>
          Effective Date: March 23, 2026
        </p>

        <p style={{ marginBottom: '32px' }}>
          AutoStudyAI is designed to help students learn more effectively. We believe in supporting
          honest academic effort and responsible use of AI-powered study tools. This Honor Code outlines
          the principles and expectations for using AutoStudyAI ethically.
        </p>

        <Section title="1. AutoStudyAI Is a Study Aid">
          <p>AutoStudyAI generates study guides, flashcards, notes, and practice questions to help you understand and retain course material. It is a supplement to your learning process — not a replacement for attending class, doing assignments, or engaging with your coursework.</p>
        </Section>

        <Section title="2. Your Responsibility">
          <p>As a user, you are responsible for how you use the materials generated by AutoStudyAI. You agree to:</p>
          <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
            <li>Use generated materials for personal study and review purposes</li>
            <li>Comply with your institution's academic integrity policies at all times</li>
            <li>Not submit AI-generated content as your own original work on assignments, papers, or exams</li>
            <li>Not use AutoStudyAI during closed-book or proctored examinations unless explicitly permitted</li>
            <li>Verify important information with your course materials and authoritative sources</li>
          </ul>
        </Section>

        <Section title="3. Prohibited Uses">
          <p>The following uses of AutoStudyAI violate this Honor Code:</p>
          <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
            <li>Copying AI-generated study guides or answers directly into graded assignments</li>
            <li>Using the extension to capture and generate answers during live exams or quizzes</li>
            <li>Sharing generated exam practice questions with others as if they are real exam content</li>
            <li>Using the platform to circumvent any learning management system's academic integrity features</li>
          </ul>
        </Section>

        <Section title="4. Intended Use Cases">
          <p>AutoStudyAI is designed for these legitimate study activities:</p>
          <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
            <li>Reviewing lecture slides and generating study guides for exam preparation</li>
            <li>Creating flashcards from course material for spaced repetition</li>
            <li>Practicing with AI-generated questions to test your understanding</li>
            <li>Summarizing dense reading material to identify key concepts</li>
            <li>Preparing for professional certification exams (NCLEX, NAPLEX, Bar, etc.)</li>
          </ul>
        </Section>

        <Section title="5. AI Limitations">
          <p>AI-generated content may contain errors or inaccuracies. AutoStudyAI should never be your sole source of information for critical decisions, professional practice, or patient care. Always cross-reference with your textbooks, instructors, and authoritative sources.</p>
        </Section>

        <Section title="6. Reporting Concerns">
          <p>If you believe AutoStudyAI is being used in violation of academic integrity policies, or if you have concerns about the platform's impact on academic honesty, please contact us at support@autostudyai.com.</p>
        </Section>

        <div style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid var(--border-subtle)' }}>
          <a href="/privacy" style={{ color: 'var(--accent)', marginRight: '16px', fontSize: '0.9rem' }}>Privacy Policy</a>
          <a href="/terms" style={{ color: 'var(--accent)', fontSize: '0.9rem' }}>Terms of Service</a>
        </div>
      </div>
    </>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: '32px' }}>
      <h2 style={{ fontSize: '1.2rem', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '12px' }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
