import Head from 'next/head';

export default function TermsOfService() {
  return (
    <>
      <Head>
        <title>Terms of Service — AutoStudyAI</title>
        <meta name="description" content="AutoStudyAI Terms of Service" />
      </Head>
      <div style={{
        maxWidth: '800px',
        margin: '0 auto',
        padding: '60px 24px',
        fontFamily: "'Segoe UI', -apple-system, sans-serif",
        color: 'var(--text-secondary)',
        lineHeight: '1.8',
      }}>
        <h1 style={{ fontSize: '2rem', fontWeight: '700', color: 'var(--text-primary)', marginBottom: '8px' }}>
          Terms of Service
        </h1>
        <p style={{ color: 'var(--text-muted)', marginBottom: '40px', fontSize: '0.9rem' }}>
          Effective Date: March 23, 2026 &nbsp;|&nbsp; Last Updated: March 23, 2026
        </p>

        <p style={{ marginBottom: '32px' }}>
          Welcome to AutoStudyAI. By accessing or using the AutoStudyAI Chrome extension
          and web platform (collectively, the "Service"), you agree to be bound by these Terms
          of Service ("Terms"). If you do not agree to these Terms, do not use the Service.
        </p>

        <Section title="1. Eligibility">
          <p>You must be at least 13 years old to use the Service. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf.</p>
        </Section>

        <Section title="2. Account Registration">
          <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You agree to provide accurate information and to notify us promptly of any unauthorized use of your account.</p>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You agree not to:</p>
          <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
            <li>Use the Service to violate any applicable law or regulation</li>
            <li>Upload malicious content, malware, or attempt to interfere with the Service</li>
            <li>Attempt to access other users' accounts or data</li>
            <li>Reverse-engineer, decompile, or disassemble the Service</li>
            <li>Use automated scripts or bots to access the Service beyond normal extension usage</li>
            <li>Resell or redistribute generated study materials commercially without permission</li>
          </ul>
        </Section>

        <Section title="4. Content and Intellectual Property">
          <p>You retain ownership of the original content you capture through the extension. Study guides, notes, and flashcards generated by the AI are provided for your personal educational use. AutoStudyAI does not claim ownership of your generated materials.</p>
          <p style={{ marginTop: '12px' }}>The Service itself, including its design, code, branding, and documentation, is the property of AutoStudyAI and is protected by intellectual property laws.</p>
        </Section>

        <Section title="5. AI-Generated Content Disclaimer">
          <p>Study materials generated by AutoStudyAI are produced by artificial intelligence and are intended as study aids only. We do not guarantee the accuracy, completeness, or correctness of any AI-generated content. You should always verify important information with authoritative sources, especially for professional certification exam preparation.</p>
        </Section>

        <Section title="6. Subscription and Billing">
          <p>AutoStudyAI offers a free tier and a paid Pro subscription. The free tier includes a limited number of guide generations per month. The Pro subscription provides unlimited generations and is billed monthly via Stripe.</p>
          <p style={{ marginTop: '12px' }}>You may cancel your subscription at any time. Upon cancellation, you will retain Pro access until the end of your current billing period. Refunds are not provided for partial billing periods.</p>
        </Section>

        <Section title="7. Termination">
          <p>We may suspend or terminate your account if you violate these Terms or engage in activity that harms the Service or other users. You may delete your account at any time by contacting us. Upon termination, your saved study materials may be permanently deleted.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>To the maximum extent permitted by law, AutoStudyAI and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
        </Section>

        <Section title="9. Disclaimer of Warranties">
          <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate or suitable for any particular purpose.</p>
        </Section>

        <Section title="10. Changes to These Terms">
          <p>We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on this page with a revised effective date. Your continued use of the Service after changes become effective constitutes your acceptance of the revised Terms.</p>
        </Section>

        <Section title="11. Governing Law">
          <p>These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles.</p>
        </Section>

        <Section title="12. Contact">
          <p>If you have questions about these Terms, please contact us at support@autostudyai.com.</p>
        </Section>

        <div style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid var(--border-subtle)' }}>
          <a href="/privacy" style={{ color: 'var(--accent)', marginRight: '16px', fontSize: '0.9rem' }}>Privacy Policy</a>
          <a href="/honor-code" style={{ color: 'var(--accent)', fontSize: '0.9rem' }}>Honor Code</a>
        </div>
      </div>
    </>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: '32px' }}>
      <h2 style={{ fontSize: '1.2rem', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '12px' }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
